notification_channels:
  - name: Mattermost
    type: webhook
    secret_name: MATTERMOST_WEBHOOK_URL
    is_default: true

monitors:
  - name: Google
    type: http
    mode: external
    visibility: public
    target: https://www.google.com/generate_204
    interval: 60s
    alerts:
      - condition: "status != 200"
        severity: critical
        failures: 2
        recovery: 2
        cooldown: 300s
  - name: Google DNS
    type: dns
    mode: external
    visibility: public
    target: google.com
    interval: 60s
    alerts:
      - condition: "status != up"
        severity: critical
        failures: 2
        recovery: 2
        cooldown: 300s
  - name: Gmail SMTP
    type: tcp
    mode: external
    visibility: public
    target: smtp.gmail.com:587
    interval: 60s
    alerts:
      - condition: "connect != true"
        severity: critical
        failures: 2
        recovery: 2
        cooldown: 300s
